FPS = 60



SCREEN_SIZE = (1200, 800)
WIDTH, HEIGHT = 1200, 800



AIM_SIZE = (30, 30)
AIM_SIZE_HALF = (AIM_SIZE[0] // 2, AIM_SIZE[1] // 2)



V = 200



GAME_FIELD_WIDTH = 800 - 50
GAME_FILED_HEIGHT = HEIGHT - 50
GAME_FIELD = (GAME_FIELD_WIDTH, GAME_FILED_HEIGHT)



# --- INFO BOARD ---
INFO_BOARD_X = GAME_FIELD_WIDTH + 100
INFO_BOARD_Y = GAME_FILED_HEIGHT + 100


INFO_BOARD_TIME_TEXT_X = INFO_BOARD_X + 150
INFO_BOARD_TIME_TEXT_Y = HEIGHT // 2
INFO_BOARD_TIME_TEXT_COLOR = "black"


INFO_BOARD_SCORE_TEXT_X = INFO_BOARD_TIME_TEXT_X
INFO_BOARD_SCORE_TEXT_Y = INFO_BOARD_TIME_TEXT_Y + 50
INFO_BOARD_SCORE_TEXT_COLOR = "black"


INFO_BOARD_RECT_X = INFO_BOARD_X + 70
INFO_BOARD_RECT_Y = 50

INFO_BOARD_RECT_WIDTH = 200
INFO_BOARD_RECT_HEIGHT = 200


INFO_BOARD_RECT_COLOR = "black"



# --- MAIN MENU ---
MAIN_MENU_SCORE_PLAY_TEXT_X = 600
MAIN_MENU_SCORE_PLAY_TEXT_Y = 400

MAIN_MENU_SCORE_PLAY_TEXT_COLOR = "black"


MAIN_MENU_SCORE_PLAY_RECT_WIDTH = 300
MAIN_MENU_SCORE_PLAY_RECT_HEIGHT = 100

MAIN_MENU_SCORE_PLAY_RECT_X = 450
MAIN_MENU_SCORE_PLAY_RECT_Y = 350

MAIN_MENU_SCORE_PLAY_RECT_COLOR = "black"


MAIN_MENU_SCORE_BEST_SCORE_TEXT_X = 450
MAIN_MENU_SCORE_BEST_SCORE_TEXT_Y = 350



DIRECTORY_HEROES_ANIMATION_SMALL_NAME = r"data\heroes_1\heroes_animation_small"
DIRECTORY_HEROES_LARGE_NAME = r"data\heroes_1\heroes_large"